### ISSUE TITLE
Can not download from main web site

### ISSUE THREAD

**Issue by tseemann** [GuillaumeHolley/BlastGraph#1]
Clicking on http://alcovna.genouest.org/blastgraph/ gives "This site can not be reached"

ping fails.

traceroute is very confused.

Is the server down?

**Comment by GuillaumeHolley** [comment]
Unfortunately, yes. Alcovna was the program financing this project, it ended few years ago. It is why the server is down (and will stay down). The only way to access the code now is via this GitHub account.
